=== BackupTheBerlios/unisimu-svn/Methodology/Kid/Kid.dtd
<?xml version="1.0"?>

<!ELEMENT program          (statement_list)>
<!ELEMENT statement_list   (statement+)>
<!ELEMENT statement        (assignment | if_statement | block | declaration | comment)>
<!ELEMENT assignment       (var | expression)>
<!ELEMENT var              (identifier)>
<!ELEMENT identifier       (#PCDATA)>
<!ELEMENT expression       (neg?, (term, op)*, term)>
<!ELEMENT neg              (#PCDATA)>
<!ELEMENT term             ((factor, op)*, factor)>
<!ELEMENT factor           (number | expression | proc_call | var)>
<!ELEMENT number           (#PCDATA)>
<!ELEMENT proc_call        (identifier, expression_list)>
<!ELEMENT expression_list  (expression+)>
<!ELEMENT op               (#PCDATA)>
<!ELEMENT if_statement     (condition, statement, statement?)>
<!ELEMENT condition        (expression, rel_op, expression)>
<!ELEMENT rel_op           (#PCDATA)>
<!ELEMENT block            (statement_list)>
<!ELEMENT declaration      (proc_decl)>
<!ELEMENT proc_decl        (identifier, identifier_list, block)>
<!ELEMENT identifier_list  (identifier+)>
<!ELEMENT comment          (#PCDATA)>

=== BackupTheBerlios/unisimu-svn/Methodology/Kid/t/script/~02test.xml
<?xml version="1.0"?>
<!DOCTYPE program SYSTEM "Kid.dtd">
<program>
<statement_list>
<statement>
<if_statement>
<condition>
<expression>
<term>
<factor>
<var>
<identifier>x</identifier>
</var>
</factor>
</term>
</expression>
<rel_op>&gt;</rel_op>
<expression>
<term>
<factor>
<number>0</number>
</factor>
</term>
</expression>
</condition>
<statement>
<block>
<statement_list>
<statement>
<assignment>
<var>
<identifier>x</identifier>
</var>
<expression>
<term>
<factor>
<var>
<identifier>x</identifier>
</var>
</factor>
</term>
<op>+</op>
<term>
<factor>
<number>2</number>
</factor>
</term>
</expression>
</assignment>
</statement>
<statement>
<if_statement>
<condition>
<expression>
<term>
<factor>
<var>
<identifier>x</identifier>
</var>
</factor>
</term>
</expression>
<rel_op>&lt;=</rel_op>
<expression>
<term>
<factor>
<var>
<identifier>y</identifier>
</var>
</factor>
</term>
</expression>
</condition>
<statement>
<block>
<statement_list>
<statement>
<assignment>
<var>
<identifier>y</identifier>
</var>
<expression>
<term>
<factor>
<var>
<identifier>x</identifier>
</var>
</factor>
</term>
</expression>
</assignment>
</statement>
</statement_list>
</block>
</statement>
</if_statement>
</statement>
</statement_list>
</block>
</statement>
</if_statement>
</statement>
</statement_list>
</program>
